package com.michaelrmossman.collections.data

import com.michaelrmossman.collections.database.HistoryDao
import com.michaelrmossman.collections.enum.Media
import kotlinx.coroutines.flow.Flow

class HistoryRepository(
    private val historyDao: HistoryDao
) {

    suspend fun deleteAllHistoryItems(): Int =
        historyDao.deleteAllHistoryItems()

    suspend fun getHistoryItemsByMediaType(
        media: Media? // MediaType?
    ) : List<String> = historyDao.getHistoryItemsByMedia(
        media = media?.toString() ?: String()
    )

    fun getHistoryItemsCount(): Flow<Int> =
        historyDao.getHistoryItemsCount()

    suspend fun insertHistoryItem(
        item: String, media: Media? // MediaType?
    ) {
        val mediaName = media?.toString() ?: String()
        if (!historyDao.historyItemExists(
            /* Database query also specifies LOWER() */
            item = item.lowercase(),
            media = mediaName
        )) {
            val historyEntity = HistoryEntity(
                historyId = 0, /* autoGenerated */
                media = mediaName,
                historyItem = item.lowercase()
            )
            historyDao.insertHistoryItem(historyEntity)
        }
    }
}